### PR TITLE
Progress bar and Grunt fixes

### PR DESCRIPTION
**Pull request by ghost**
The primary changes of this pull request are:

- Fix the progress bar loading. There were still some minor problems
- Add a sourceMap for better debugging
- Don't track minified files. The reason is when I pull and merge, there will be a conflict and I just end up deleting the files anyways because the builds will always be different whenever we make a new commit

A fix to jmickle66666666/wad-js#41

### CODE REVIEW

**Comment by jmickle66666666** [comment]
Ok, since the .min.js files are needed for the github.io page to work, I've created a new branch `develop` for development, and the gh-pages branch I will update only for tested updates to the tool.

**Comment by ghost** [comment]
That's a good solution. The best part is that we can add a command to Grunt that will automatically checkout gh-pages and build.

**Comment by jmickle66666666** [comment]
Oh wow, I didn't realise grunt was capable of that! Excellent stuff. 

Re: the text scrolling: it still doesn't work for me on OSX/Chrome. Not sure what's causing it but CSS is still a dark art to me haha

**Comment by ghost** [comment]
This information may be outdated, but it appears that the scrollbar doesn't appear on OSX unless you hover over the textPreview. Can you confirm? Also the text file I'm clicking on is DMXGUS.

**Comment by jmickle66666666** [comment]
The scrollbar doesn't normally appear, yes, but I was not able to scroll the elements at all. However, it appears I forgot to clear my cache, as it is working correctly now.

**Pull request merged**
